services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  CodingFreaks\CfPhpinclude\:
    resource: '../Classes/*'

  CodingFreaks\CfPhpinclude\Controller\PhpFrontendController:
    public: true

  CodingFreaks\CfPhpinclude\Updates\PluginListToCTypeUpdateWizard:
    class: CodingFreaks\CfPhpinclude\Updates\PluginListToCTypeUpdateWizard
    autowire: true
    public: true
    tags:
      - name: typo3.install.updatewizard